asset/urls.py
from django.conf.urls import url, include
from views import *
from rest_framework.routers import SimpleRouter
from rest_framework.documentation import include_docs_urls

# Create a router and register our viewsets with it.
router = SimpleRouter()
router.register(r'api', AssetViewSet, base_name='asset')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^idc/$', idc, name='idc'),
    url(r'^idc/add/$', addIDC, name='add_idc'),
    url(r'^idc/edit/(?P<pk>\d+)/$', editIDC, name='edit_idc'),
    url(r'^idc/del/(?P<pk>\d+)/$', delIDC, name='del_idc'),
    url(r'^ps/$', physical_server, name='ps'),
    url(r'^ps/add/$', addPS, name='add_ps'),
    url(r'^ps/edit/(?P<pk>\d+)/$', editPS, name='edit_ps'),
    url(r'^ps/del/(?P<pk>\d+)/$', delPS, name='del_ps'),
    url(r'^ps/import/$', ps_import, name='ps_import'),
    url(r'^ps/export/$', ps_export, name='ps_export'),
    url(r'^list/$', listAsset, name='list'),
    url(r'^add/$', addAsset, name='add'),
    url(r'^edit/(?P<pk>\d+)/$', editAsset, name='edit'),
    url(r'^del/(?P<pk>\d+)/$', delAsset, name='del'),
    url(r'^hostname/$', hostname, name='hostname'),
    url(r'^docs/', include_docs_urls(
                            title='Asset API Documentation', 
                            description='This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions',
                        )
    ),
]

# Generic Error Views for API-only application
#handler500 = 'rest_framework.exceptions.server_error'
#handler400 = 'rest_framework.exceptions.bad_request'

cmdb/urls.py
from views import *
from django.conf.urls import url
from django.contrib import admin
from views import CustomLoginView
from django.conf.urls import include
from django.views.static import serve
from django.contrib.auth.views import logout_then_login

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asset/', include('asset.urls')),
    url(r'^salt/', include('salts.urls')),
    url(r'^zabbix/', include('zabbix.urls')),
    url(r'^permission/', include('rbac.urls', namespace='rbac')),
    url(r'^$', index, name='index'),
    url(r'login/$', CustomLoginView.as_view(), name='loginview'),
    url(r'^logout/$', logout_then_login, name='logoutview'),
    url(r'^image/$', image, name='image'),
    url(r'^verify/$', verify, name='verify'),
    url(r'^password/$', verify_password, name='password'),
    url(r'^tpl/(\w+.(xls|xlsx))$', tpl_download, name='tpl'),
    url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^(?P<path>favicon.ico)/$', serve, {
        'document_root': 'shared_static'
    }),
]

rbac/urls.py
from django.conf.urls import url, include
from views import *


urlpatterns = [
    url(r'^menu/list/$', listMenu, name='list_menu'),
    url(r'^menu/add/$', addMenu, name='add_menu'),
    url(r'^menu/edit/(?P<pk>\d+)/$', editMenu, name='edit_menu'),
    url(r'^menu/delete/(?P<pk>\d+)/$', deleteMenu, name='delete_menu'),
    url(r'^second/menu/add/(?P<mid>\d+)/$', addSecondGradeMenu, name='add_second_menu'),
    url(r'^second/menu/edit/(?P<pk>\d+)/$', editSecondGradeMenu, name='edit_second_menu'),
    url(r'^second/menu/delete/(?P<pk>\d+)/$', deleteSecondGradeMenu, name='delete_second_menu'),
    url(r'^add/(?P<sid>\d+)/$', addPermission, name='add_permission'),
    url(r'^edit/(?P<pk>\d+)/$', editPermission, name='edit_permission'),
    url(r'^delete/(?P<pk>\d+)/$', deleteSecondGradeMenu, name='delete_permission'),
    url(r'multi/permissions/$', multiPermission, name='multi-permission'),
    url(r'^role/list/$', RoleList.as_view(), name='list_role'),
    url(r'^role/add/$', RoleCreate.as_view(), name='add_role'),
    url(r'^role/edit/(?P<pk>\d+)/$', RoleUpdate.as_view(), name='edit_role'),
    url(r'^role/delete/(?P<pk>\d+)/$', RoleDelete.as_view(), name='delete_role'),
    url(r'^assign/permissions/$', assignPermission, name='assign-permission'),
]

rbac/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

# Create your models here.

class MyUser(models.Model):
    '''
    It should use OneToOneField instead of ForeignKey to define name field
    And implementate DDL for this model.
    '''
    name = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_staff': True},
        verbose_name=u'用户名'
    )
    role = models.ManyToManyField('Role', verbose_name=u'一个用户拥有若干角色', blank=True)

    def __str__(self):
        return self.name.username

class Role(models.Model):
    name = models.CharField(max_length=16, unique=True, verbose_name=u'角色名')
    purview = models.ManyToManyField('Permission', verbose_name=u'一个角色拥有若干权限', blank=True)

    def __str__(self):
        return self.name

class Menu(models.Model):
    title = models.CharField(max_length=64, verbose_name=u'一级菜单')
    icon = models.CharField(blank=True, max_length=16, help_text=u'应填写ICON 名称，例如icon-home，参考ZUI框架文档-控件-图标')

    def __unicode__(self):
        return self.title

class Permission(models.Model):
    description = models.CharField(max_length=64, verbose_name=u'权限描述')
    url = models.CharField(max_length=64, blank=True, verbose_name=u'含正则的URL')
    url_pattern_name = models.CharField(blank=True, max_length=32, help_text = u'应与urls.py 里定义的url pattern name 完全一致')
    icon = models.CharField(blank=True, max_length=32)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True, blank=True, help_text=u'menu 为null 表示非菜单')
    related_id = models.ForeignKey(
        to='Permission',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name=u'非菜单关联的权限',
        help_text = u'对于部分非菜单权限，应为其展开关联的菜单权限',
        limit_choices_to={'menu__isnull': False}  
    )

    def __unicode__(self):
        return self.description

rbac/forms.py
#!/usr/bin/env python
#coding: utf8

from cmdb.utils import AddClass
from models import Menu, Permission, Role
from django.forms import ModelForm, ValidationError, TextInput

class AddMenuForm(ModelForm):
    class Meta:
        model = Menu
        fields = ['title', 'icon']

    def __init__(self, *args, **kwargs):
        super(AddMenuForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class SecondGradeMenuForm(ModelForm):
    class Meta:
        model = Permission
        exclude = ['related_id']

    def __init__(self, *args, **kwargs):
        super(SecondGradeMenuForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class PermissionForm(ModelForm):
    class Meta:
        model = Permission
        fields = ['description', 'url', 'icon', 'url_pattern_name']

    def __init__(self, *args, **kwargs):
        super(PermissionForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class MultiPermissionForm(ModelForm):
    class Meta:
        model = Permission
        exclude = ['icon']

    def __init__(self, *args, **kwargs):
        super(MultiPermissionForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class RoleForm(ModelForm):
    class Meta:
        model = Role
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
        }

rbac/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import time
from django.urls import reverse
from cmdb.utils import getAllURLs
from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from models import Menu, Permission, Role, MyUser
from django.utils.module_loading import import_string
from django.views.decorators.http import require_POST
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from forms import AddMenuForm, SecondGradeMenuForm, PermissionForm, MultiPermissionForm, RoleForm

# Create your views here.

def customReverse(request, viewname, *args, **kwargs):
    url = reverse(viewname, *args, **kwargs)
    query_params = request.GET.get('source')
    if query_params:
        url = '{0}?{1}'.format(url, query_params)
    return url

def listMenu(request):
    menu_list = Menu.objects.all()
    menu_id = request.GET.get('mid')
    second_grade_menu_id = request.GET.get('sid')
    second_grade_menu_list = Permission.objects.filter(menu_id=menu_id) if menu_id else Permission.objects.none()
    not_menu_permission_list = Permission.objects.filter(related_id_id=second_grade_menu_id) if second_grade_menu_id else Permission.objects.none()
    add_menu_form = AddMenuForm()
    permission_form = PermissionForm()
    return render(request, 'rbac/menu_list.html', locals())

@require_POST
def addMenu(request):
    form = AddMenuForm(request.POST)
    if form.is_valid():
        new_object = form.save()
        return redirect(customReverse(request, 'rbac:list_menu'))

def editMenu(request, pk):
    menu = Menu.objects.get(id=pk)
    if request.method == 'POST':
        form = AddMenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = AddMenuForm(instance=menu)
    return render(request, 'rbac/edit.html', locals())

def deleteMenu(request, pk):
    Menu.objects.get(id=pk).delete()
    return redirect(reverse('rbac:list_menu'))

def addSecondGradeMenu(request, mid):
    menu = Menu.objects.get(id=mid)
    form = SecondGradeMenuForm(initial={'menu': menu})
    if request.method == 'POST':
        form = SecondGradeMenuForm(request.POST)
        if form.is_valid():
            new_nemu = form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    return render(request, 'rbac/add_second_menu.html', locals())

def editSecondGradeMenu(request, pk):
    perm = Permission.objects.get(id=pk)
    if request.method == 'POST':
        form = SecondGradeMenuForm(request.POST, instance=perm)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = SecondGradeMenuForm(instance=perm)
    return render(request, 'rbac/add_second_menu.html', locals())

def deleteSecondGradeMenu(request, pk):
    Permission.objects.get(id=pk).delete()
    return redirect(customReverse(request, 'rbac:list_menu'))

@require_POST
def addPermission(request, sid):
    second_grade_menu = Permission.objects.get(id=sid)
    form = PermissionForm(request.POST)
    if form.is_valid():
        form.instance.related_id = second_grade_menu
        new_object = form.save()
        return redirect(customReverse(request, 'rbac:list_menu'))

def editPermission(request, pk):
    perm = Permission.objects.get(id=pk)
    if request.method == 'POST':
        form = PermissionForm(request.POST, instance=perm)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = PermissionForm(instance=perm)
    return render(request, 'rbac/edit.html', locals())

def multiPermission(request):
    _type = request.GET.get('type', None)    # Type identify which form was posted

    # Get the app's url patterns which has installed
    url_dict = dict()
    urls = import_string(dotted_path=settings.ROOT_URLCONF)
    getAllURLs(urls.urlpatterns, url_dict, prefix='/')
    router_url_pattern_set = set(url_dict.keys())
    
    # Get the url info in database
    permission_dict = Permission.objects.exclude(url='/').values('id', 'url', 'url_pattern_name', 'description', 'menu', 'related_id')
    permission_url_pattern_set = set()
    for item in permission_dict:
        permission_url_pattern_set.add(item['url_pattern_name'])

    # Compare url_dict and permission_dict
    for item in permission_dict:
        router_obj = url_dict.get(item['url_pattern_name'], None)
        if router_obj is not None:
            if item['url'] != router_obj['url']:
                item['url'] = u'路由url和数据库中的url不一致'

    # URLs pattern should be added to database
    add_url_name_set = router_url_pattern_set - permission_url_pattern_set
    init_data = [value for key, value in url_dict.items() if key in add_url_name_set]
    PermissionAddFormSet = modelformset_factory(
        model=Permission,
        form=MultiPermissionForm,
        extra=len(init_data))
    if _type is not None and _type == 'add' and request.method == 'POST':
        formset_add = PermissionAddFormSet(request.POST, initial=init_data) 
        if formset_add.is_valid():
            formset_add.save()
            return redirect(customReverse(request, 'rbac:list_menu'))   
    else:
        formset_add = PermissionAddFormSet(
            initial=init_data,
            queryset=Permission.objects.none())
    
    # URLs pattern should be deleted from database
    delete_url_name_set = permission_url_pattern_set - router_url_pattern_set
    delete_url_list = [row for row in permission_dict if row['url_pattern_name'] in delete_url_name_set]

    # URLs pattern might be update to database
    might_update_url_set = permission_url_pattern_set & router_url_pattern_set
    update_queryset = Permission.objects.none()
    for update_item in permission_dict:
        url_name = update_item['url_pattern_name']
        if url_name in might_update_url_set:
            update_queryset = update_queryset.union(Permission.objects.filter(url_pattern_name=url_name))
    PermissionUpdateFormSet = modelformset_factory(
        model=Permission,
        form=MultiPermissionForm,
        extra=0)
    if _type is not None and _type == 'update' and request.method == 'POST':
        formset_update = PermissionUpdateFormSet(request.POST)
        if formset_update.is_valid():
            formset_update.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        formset_update = PermissionUpdateFormSet(queryset=update_queryset)

    return render(request, 'rbac/operate_multi_permission.html', locals())

class RoleList(ListView):
    model = Role

    def get_context_data(self, **kwargs):
        context = super(RoleList, self).get_context_data(**kwargs)
        context['form'] = RoleForm()
        return context

class RoleCreate(CreateView):
    model = Role
    form_class = RoleForm

class RoleUpdate(UpdateView):
    model = Role
    form_class = RoleForm
    template_name = 'rbac/edit.html'

class RoleDelete(DeleteView):
    model = Role
    success_url = reverse_lazy('rbac:list_role')

def assignPermission(request):
    user_id = request.GET.get('uid')
    user_list = MyUser.objects.all()
    if user_id is not None:
        user_obj = user_list.get(pk=user_id)
    else:
        user_obj = None

    role_id = request.GET.get('rid')
    role_list = Role.objects.all()
    if role_id is not None:
        role_obj = role_list.get(pk=role_id)
    else:
        role_obj = None

    user_roles = user_obj.role.all() if user_id else Role.objects.none()
    user_role_list = [i.id for i in user_roles] if user_roles else []

    # Save roles belong to user_obj
    if request.method == 'POST' and request.POST.get('type') == 'role':
        posted_role_list = request.POST.getlist('role')
        user_obj.role.set(posted_role_list)
        time.sleep(2)
        return redirect(request.get_full_path())

    # Save permissions belong to its role
    if request.method == 'POST' and request.POST.get('type') == 'permission':
        posted_permission_list = request.POST.getlist('permission')
        role_obj.purview.set(posted_permission_list)
        time.sleep(2)
        return redirect(request.get_full_path())

    # When chose a role, show all permissions belong to it,
    # otherwise to a user
    if role_obj:
        user_permission_list = [perm.id for perm in role_obj.purview.all()]
    elif user_obj:
        user_permission_list = [item['purview'] for item in user_obj.role.values('purview')]
    else:
        user_permission_list = list()

    # One grade menu
    all_menu_list = Menu.objects.values('id', 'title')
    all_menu_dict = dict()
    for item in all_menu_list:
        item['children'] = list()
        all_menu_dict[item['id']] = item

    # Second grade menu
    all_second_menu_list = Permission.objects.filter(menu__isnull=False).values('id', 'description', 'menu_id')
    all_second_menu_dict = dict()
    for s_item in all_second_menu_list:
        s_item['children'] = list()
        all_second_menu_dict[s_item['id']] = s_item
        menu_id = s_item['menu_id']
        all_menu_dict[menu_id]['children'].append(s_item)
        # all_menu_dict[menu_id] == all_menu_dict[item['id']]

    # All permissions which can not be menu
    all_permission_list = Permission.objects.filter(menu__isnull=True).values('id', 'description', 'related_id_id')
    for p_item in all_permission_list:
        related_id = p_item['related_id_id']
        if related_id is not None:
            all_second_menu_dict[related_id]['children'].append(p_item)
            # all_second_menu_dict[related_id] == all_second_menu_dict[s_item['id']] == s_item
            # all_menu_dict[menu_id]['children'].append(all_second_menu_dict[related_id])

    '''

templates/rbac/add_second_menu.html
{% extends "rbac/base_permission.html" %}
{% block content %}
  <div>
    <form method="post" action="" class="form-horizontal" role="form">
      <div class="form-group">
        <label class="col-sm-2"></label>
        <div class="col-md-6 col-sm-10">
          <h3>添加或修改二级菜单</h3>
        </div>
      </div>
      {% csrf_token %}
      {% include "forms.html" %}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

templates/rbac/base_permission.html
<!DOCTYPE html>
<html>
<head lang="zh-cn">
    {% load static customtags %}
    <meta charset="utf8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 响应式设计标签 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ZUI 标准版压缩后的 CSS 文件 -->
    <link rel="stylesheet" href="//cdn.bootcss.com/zui/1.8.1/css/zui.min.css">

    <!-- ZUI Javascript 依赖 jQuery -->
    <script src="//cdn.bootcss.com/zui/1.8.1/lib/jquery/jquery.js"></script>
    <!-- ZUI 标准版压缩后的 JavaScript 文件 -->
    <script src="//cdn.bootcss.com/zui/1.8.1/js/zui.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/main.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
{% block msg %}{% endblock %}
{% block header %}
  {% include "header.html" %}
{% endblock %}
  <div class="container">
    <div class="left">
      <div class="sidebar">
        <nav class="menu" data-ride="menu" style="width: 200px">
          <ul id="treeMenu" class="tree tree-menu" data-ride="tree">
            <li><a href="{% url 'rbac:list_menu' %}"><i class="icon icon-lock"></i>权限管理</a></li>
            <li><a href="{% url 'rbac:assign-permission' %}"><i class="icon icon-lock"></i>权限分配</a></li>
            <li><a href="{% url 'oauth2_provider:list' %}"><i class="icon icon-asterisk"></i>应用管理</a></li>
            <li><a href="{% url 'rbac:list_role' %}"><i class="icon icon-anchor"></i>角色管理</a></li>
            <li><a href="/admin/"><i class="icon icon-user"></i>用户管理</a></li>
          </ul>
        </nav>
      </div>
    </div>
  
    <div class="right">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>

templates/rbac/breadcrumb.html
{% if breadcrumb_list|length != 1 %}
  <ol class="breadcrumb">
    {% for i in breadcrumb_list %}
      {% if i.class %}
        <li class="{{ i.class }}">{{ i.title }}</li>
      {% else %}
        <li><a href="{{ i.url }}">{{ i.title }}</a></li>
      {% endif %}
    {% endfor %}
  </ol>
{% endif %}

templates/rbac/edit.html
{% extends "rbac/base_permission.html" %}
{% block content %}
  <form method="post" action="" class="form-horizontal" role="form">
    <div class="form-group">
      <label class="col-sm-2"></label>
      <div class="col-md-6 col-sm-10">
        <h3>编辑一级菜单|权限|角色</h3>
      </div>
    </div>
    {% csrf_token %}
    {% include "forms.html" %}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">提交</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/rbac/operate_multi_permission.html
{% extends "rbac/base_permission.html" %}
{% block head %}
<script>
    $(function () {
        $("a.delete").click(function (e) {
            var action = confirm("确认删除？");
            if (action == false) {
                e.preventDefault()
            }
        })
    })
</script>
<style>
  td {text-align: left;}
</style>
{% endblock %}
{% block content %}
  <form method="post" action="?type=add">
    {% csrf_token %}
    {{ formset_add.management_form }}
    <div class="panel panel-success">
      <div class="panel-heading">
        <span><i class="icon icon-tag"></i> 待新增权限</span>
        <button type="submit" class="btn btn-success btn-sm pull-right"><i class="icon icon-save"></i> 新增</button>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>序号</th>
            <th>名称</th>
            <th>URL</th>
            <th>URL Name</th>
            <th>所属菜单</th>
            <th>关联的菜单</th>
          </tr>
        </thead>
        <tbody>
          {% for form in formset_add %}
            <tr>
              <td>{{ forloop.counter }}</td>
              {% for field in form %}
                <td>{{ field }}</td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>

  <div class="panel panel-danger">
    <div class="panel-heading">
      <span><i class="icon icon-eye-open"></i> 待删除权限</span>
      <a href="#" class="btn btn-danger btn-sm pull-right"><i class="icon icon-remove-sign"></i> 删除</a>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>序号</th>
          <th>名称</th>
          <th>URL</th>
          <th>URL Name</th>
          <th>删除</th>
        </tr>
      </thead>
      <tbody>
        {% for item in delete_url_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.url_pattern_name }}</td>
            <td><a href="{% url 'rbac:delete_permission' item.id %}" class="delete"><i class="icon icon-trash"></i></a></td>
          </td>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <form method="post" action="?type=update">
    {% csrf_token %}
    {{ formset_update.management_form }}
    <div class="panel panel-info">
      <div class="panel-heading">
        <span><i class="icon icon-eye-close"></i> 可能更新的权限</span>
        <button type="submit" class="btn btn-info btn-sm pull-right"><i class="icon icon-save"></i> 更新</button>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>序号</th>
            <th>名称</th>
            <th>URL</th>
            <th>URL Name</th>
            <th>所属菜单</th>
            <th>关联的菜单</th>
          </tr>
        </thead>
        <tbody>
          {% for form in formset_update %}
            <tr>
              <td>{{ forloop.counter }}</td>
                {% for field in form %}
                  <td>{{ field }}</td>
                {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>

{% endblock %}

templates/rbac/role_list.html
{% extends "rbac/base_permission.html" %}
{% load customfilters %}
{% block head %}
<script>
    $(function () {
        $("a.delete").click(function (e) {
            var action = confirm("确认删除？");
            if (action == false) {
                e.preventDefault()
            }
        })
    })
</script>
<style>
  td {text-align: left;}
  a[href="#add-role"] {margin-bottom: 10px;}
</style>
{% endblock %}
{% block content %}
  <a data-toggle="modal" href="#add-role"class="btn btn-info">添加角色</a>
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-fixed">
      <thead>
        <tr>
          <th>序号</th>
          <th>角色名</th>
          {% if request|has_permission:'编辑角色' or request|has_permission:'删除角色' %}
            <th>操作</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for role in role_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ role.name }}</td>
            {% with perm_edit=request|has_permission:'编辑角色' perm_delete=request|has_permission:'删除角色' %}
              {% if perm_edit or perm_delete %}
                <td class="action">
                  {% if perm_edit %}
                    <a href="{% url 'rbac:edit_role' role.id %}" class="btn btn-info btn-sm"><i class="icon icon-edit"></i></a>
                  {% endif %}
                  {% if perm_delete %}
                    <a href="{% url 'rbac:delete_role' role.id %}" class="delete btn btn-danger btn-sm"><i class="icon icon-trash"></i></a>
                  {% endif %}
                </td>
              {% endif %}
            {% endwith %}
          </tr>
        {% endfor %}   
      </tbody> 
    </table>
  </div>

  <div class="modal fade" id="add-role">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'rbac:add_role' %}" method="post" id="myform">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">关闭</span></button>
            <h4 class="modal-title">添加角色</h4>
          </div>
          <div class="modal-body">
            {% csrf_token %}
            {% include "forms.html" %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            <button type="submit" class="btn btn-primary">提交</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/rbac/sidebar.html
<div class="sidebar">
  <nav class="menu" data-ride="menu">
    <ul id="treeMenu" class="tree tree-menu" data-ride="tree">
      {% for item in menu_list %}
        {% if item.title == '首页' %}
            <li><a href="{% url 'index' %}"><i class="icon icon-home"></i>仪盘表</a></li>
        {% else %} 
            {% if item.class %}
              <li class="{{ item.class }}">
            {% else %}
              <li>
            {% endif %}
                <a href="javascript:void(0);"><i class="icon {{ item.icon }}"></i>{{ item.title }}</a>
                <ul>
                  {% for node in item.nodes %}
                    <li><a href="{{ node.url }}"><i class="icon {{ node.icon }}"></i>{{ node.title }}</a></li>
                  {% endfor %}
                </ul>
              </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
  <footer>
    <div class="footer">
      <p class="text-muted small">版本 <span class="doc-version">0.2.0</span></p>
    </div>
  </footer>
</div>