asset/urls.py
from django.conf.urls import url, include
from views import *
from rest_framework.routers import SimpleRouter
from rest_framework.documentation import include_docs_urls

# Create a router and register our viewsets with it.
router = SimpleRouter()
router.register(r'api', AssetViewSet, base_name='asset')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^idc/$', idc, name='idc'),
    url(r'^idc/add/$', addIDC, name='add_idc'),
    url(r'^idc/edit/(?P<pk>\d+)/$', editIDC, name='edit_idc'),
    url(r'^idc/del/(?P<pk>\d+)/$', delIDC, name='del_idc'),
    url(r'^ps/$', physical_server, name='ps'),
    url(r'^ps/add/$', addPS, name='add_ps'),
    url(r'^ps/edit/(?P<pk>\d+)/$', editPS, name='edit_ps'),
    url(r'^ps/del/(?P<pk>\d+)/$', delPS, name='del_ps'),
    url(r'^ps/import/$', ps_import, name='ps_import'),
    url(r'^ps/export/$', ps_export, name='ps_export'),
    url(r'^list/$', listAsset, name='list'),
    url(r'^add/$', addAsset, name='add'),
    url(r'^edit/(?P<pk>\d+)/$', editAsset, name='edit'),
    url(r'^del/(?P<pk>\d+)/$', delAsset, name='del'),
    url(r'^hostname/$', hostname, name='hostname'),
    url(r'^docs/', include_docs_urls(
                            title='Asset API Documentation', 
                            description='This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions',
                        )
    ),
]

# Generic Error Views for API-only application
#handler500 = 'rest_framework.exceptions.server_error'
#handler400 = 'rest_framework.exceptions.bad_request'

cmdb/urls.py
from views import *
from django.conf.urls import url
from django.contrib import admin
from views import CustomLoginView
from django.conf.urls import include
from django.views.static import serve
from django.contrib.auth.views import logout_then_login

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asset/', include('asset.urls')),
    url(r'^salt/', include('salts.urls')),
    url(r'^zabbix/', include('zabbix.urls')),
    url(r'^permission/', include('rbac.urls', namespace='rbac')),
    url(r'^$', index, name='index'),
    url(r'login/$', CustomLoginView.as_view(), name='loginview'),
    url(r'^logout/$', logout_then_login, name='logoutview'),
    url(r'^image/$', image, name='image'),
    url(r'^verify/$', verify, name='verify'),
    url(r'^password/$', verify_password, name='password'),
    url(r'^tpl/(\w+.(xls|xlsx))$', tpl_download, name='tpl'),
    url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^(?P<path>favicon.ico)/$', serve, {
        'document_root': 'shared_static'
    }),
]

asset/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

asset_env = (
    (1, U'生产环境'),
    (2, U'测试环境')
    )

asset_status = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u'待回收')
    )

ASSET_TYPE = (
    (1, u'虚拟机'),
    (2, u'交换机'),
    (3, u'路由器'),
    (4, u'其他'),
    )

class PhysicalServer(models.Model):
    manufacturer = models.CharField(max_length=32, verbose_name=u'厂商')
    model = models.CharField(max_length=64, verbose_name=u'型号')
    sn = models.CharField(max_length=64, verbose_name=u'序列号')
    ip = models.GenericIPAddressField(protocol='IPv4', verbose_name=u'IP')
    cpu = models.CharField(max_length=64, verbose_name=u'CPU')
    memory = models.CharField(max_length=32, verbose_name=u'内存')
    disk = models.CharField(max_length=32, verbose_name=u'硬盘')
    nic_num = models.PositiveIntegerField(verbose_name=u'网卡数量')
    comment = models.CharField(max_length=128, blank=True, verbose_name=u"备注")

    def __unicode__(self):
        return self.ip
    
    class Meta:
        verbose_name = u"物理服务器"
        verbose_name_plural = verbose_name

class IDC(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'机房名称')
    address = models.CharField(max_length=128, blank=True, verbose_name=u"机房地址")
    linkman = models.CharField(max_length=16, blank=True, verbose_name=u'联系人')
    ci = models.CharField(max_length=32, blank=True, verbose_name=u'联系方式')
    bandwidth = models.CharField(max_length=32, blank=True, verbose_name=u'机房带宽')
    ip_segment = models.TextField(blank=True, verbose_name=u"IP地址段")
    comment = models.CharField(max_length=128, blank=True, verbose_name=u"备注")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"IDC机房"
        verbose_name_plural = verbose_name
        ordering = ['-id']

class Asset(models.Model):
    ip = models.CharField(max_length=16, blank=True, verbose_name=u'电信IP')
    other_ip = models.CharField(max_length=16, blank=True, verbose_name=u'联通IP')
    idc = models.ForeignKey(IDC, verbose_name=u'机房')
    hostname = models.CharField(max_length=32, blank=True)
    cpu = models.CharField(max_length=32, blank=True, verbose_name=u'CPU（核数）')
    memory = models.CharField(max_length=32, blank=True, verbose_name=u'内存（GB）')
    disk = models.CharField(max_length=32, blank=True, verbose_name=u'硬盘（GB）')
    system = models.CharField(max_length=64, blank=True, verbose_name=u"系统")
    status = models.IntegerField(choices=asset_status, blank=True, default=1, verbose_name=u"机器状态")
    asset_type = models.IntegerField(choices=ASSET_TYPE, blank=True, verbose_name=u"主机类型")
    env = models.IntegerField(choices=asset_env, blank=True, verbose_name=u"运行环境")
    host = models.ForeignKey(PhysicalServer, verbose_name=u'宿主机')
    comment = models.CharField(max_length=128, blank=True, verbose_name=u"备注")
    
    def __unicode__(self):
        if self.ip:
            return self.ip
        elif self.other_ip:
            return self.other_ip
        else:
            return self.hostname

asset/forms.py
#!/usr/bin/env python
#coding:utf8

from django import forms
from cmdb.utils import validIPV4, AddClass
from models import IDC, PhysicalServer, Asset
from django.forms import ModelForm, Textarea, Select
from django.utils.translation import ugettext_lazy as _

class IdcForm(ModelForm):
    class Meta:
        model = IDC
        fields = ['name', 'address', 'linkman', 'ci', 'bandwidth', 'ip_segment', 'comment']
        widgets = {'ip_segment': Textarea}

    def __init__(self, *args, **kwargs):
        super(IdcForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class PhysicalServerForm(ModelForm):
    class Meta:
        model = PhysicalServer
        fields = ['manufacturer', 'model', 'sn', 'ip', 'cpu', 'memory', 'disk', 'nic_num', 'comment']
        error_messages = {
            'ip': {
                'invalid': _(u'IP地址不合法'),
            },
        }

    def __init__(self, *args, **kwargs):
        super(PhysicalServerForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

class AssetForm(ModelForm):
    class Meta:
        model = Asset
        fields = ['ip', 'other_ip', 'idc', 'hostname', 'cpu', 'memory', 'disk', 'system', 'status', 'asset_type', 'env', 'host', 'comment']
        widgets = {
            'status': Select(attrs={'required': True}),
            'asset_type': Select(attrs={'required': True}),
            'env': Select(attrs={'required': True})
        }

    def __init__(self, *args, **kwargs):
        super(AssetForm, self).__init__(*args, **kwargs)
        instance = AddClass(self.fields)

    def customValidIP(self, ip):
        if ip:
            if not validIPV4(ip):
                raise forms.ValidationError(u'IP地址不合法')
        return ip

    def clean_ip(self):
        return self.customValidIP(self.cleaned_data['ip'])

    def clean_other_ip(self):
        return self.customValidIP(self.cleaned_data['other_ip'])

rbac/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import time
from django.urls import reverse
from cmdb.utils import getAllURLs
from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from models import Menu, Permission, Role, MyUser
from django.utils.module_loading import import_string
from django.views.decorators.http import require_POST
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from forms import AddMenuForm, SecondGradeMenuForm, PermissionForm, MultiPermissionForm, RoleForm

# Create your views here.

def customReverse(request, viewname, *args, **kwargs):
    url = reverse(viewname, *args, **kwargs)
    query_params = request.GET.get('source')
    if query_params:
        url = '{0}?{1}'.format(url, query_params)
    return url

def listMenu(request):
    menu_list = Menu.objects.all()
    menu_id = request.GET.get('mid')
    second_grade_menu_id = request.GET.get('sid')
    second_grade_menu_list = Permission.objects.filter(menu_id=menu_id) if menu_id else Permission.objects.none()
    not_menu_permission_list = Permission.objects.filter(related_id_id=second_grade_menu_id) if second_grade_menu_id else Permission.objects.none()
    add_menu_form = AddMenuForm()
    permission_form = PermissionForm()
    return render(request, 'rbac/menu_list.html', locals())

@require_POST
def addMenu(request):
    form = AddMenuForm(request.POST)
    if form.is_valid():
        new_object = form.save()
        return redirect(customReverse(request, 'rbac:list_menu'))

def editMenu(request, pk):
    menu = Menu.objects.get(id=pk)
    if request.method == 'POST':
        form = AddMenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = AddMenuForm(instance=menu)
    return render(request, 'rbac/edit.html', locals())

def deleteMenu(request, pk):
    Menu.objects.get(id=pk).delete()
    return redirect(reverse('rbac:list_menu'))

def addSecondGradeMenu(request, mid):
    menu = Menu.objects.get(id=mid)
    form = SecondGradeMenuForm(initial={'menu': menu})
    if request.method == 'POST':
        form = SecondGradeMenuForm(request.POST)
        if form.is_valid():
            new_nemu = form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    return render(request, 'rbac/add_second_menu.html', locals())

def editSecondGradeMenu(request, pk):
    perm = Permission.objects.get(id=pk)
    if request.method == 'POST':
        form = SecondGradeMenuForm(request.POST, instance=perm)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = SecondGradeMenuForm(instance=perm)
    return render(request, 'rbac/add_second_menu.html', locals())

def deleteSecondGradeMenu(request, pk):
    Permission.objects.get(id=pk).delete()
    return redirect(customReverse(request, 'rbac:list_menu'))

@require_POST
def addPermission(request, sid):
    second_grade_menu = Permission.objects.get(id=sid)
    form = PermissionForm(request.POST)
    if form.is_valid():
        form.instance.related_id = second_grade_menu
        new_object = form.save()
        return redirect(customReverse(request, 'rbac:list_menu'))

def editPermission(request, pk):
    perm = Permission.objects.get(id=pk)
    if request.method == 'POST':
        form = PermissionForm(request.POST, instance=perm)
        if form.is_valid():
            form.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        form = PermissionForm(instance=perm)
    return render(request, 'rbac/edit.html', locals())

def multiPermission(request):
    _type = request.GET.get('type', None)    # Type identify which form was posted

    # Get the app's url patterns which has installed
    url_dict = dict()
    urls = import_string(dotted_path=settings.ROOT_URLCONF)
    getAllURLs(urls.urlpatterns, url_dict, prefix='/')
    router_url_pattern_set = set(url_dict.keys())
    
    # Get the url info in database
    permission_dict = Permission.objects.exclude(url='/').values('id', 'url', 'url_pattern_name', 'description', 'menu', 'related_id')
    permission_url_pattern_set = set()
    for item in permission_dict:
        permission_url_pattern_set.add(item['url_pattern_name'])

    # Compare url_dict and permission_dict
    for item in permission_dict:
        router_obj = url_dict.get(item['url_pattern_name'], None)
        if router_obj is not None:
            if item['url'] != router_obj['url']:
                item['url'] = u'路由url和数据库中的url不一致'

    # URLs pattern should be added to database
    add_url_name_set = router_url_pattern_set - permission_url_pattern_set
    init_data = [value for key, value in url_dict.items() if key in add_url_name_set]
    PermissionAddFormSet = modelformset_factory(
        model=Permission,
        form=MultiPermissionForm,
        extra=len(init_data))
    if _type is not None and _type == 'add' and request.method == 'POST':
        formset_add = PermissionAddFormSet(request.POST, initial=init_data) 
        if formset_add.is_valid():
            formset_add.save()
            return redirect(customReverse(request, 'rbac:list_menu'))   
    else:
        formset_add = PermissionAddFormSet(
            initial=init_data,
            queryset=Permission.objects.none())
    
    # URLs pattern should be deleted from database
    delete_url_name_set = permission_url_pattern_set - router_url_pattern_set
    delete_url_list = [row for row in permission_dict if row['url_pattern_name'] in delete_url_name_set]

    # URLs pattern might be update to database
    might_update_url_set = permission_url_pattern_set & router_url_pattern_set
    update_queryset = Permission.objects.none()
    for update_item in permission_dict:
        url_name = update_item['url_pattern_name']
        if url_name in might_update_url_set:
            update_queryset = update_queryset.union(Permission.objects.filter(url_pattern_name=url_name))
    PermissionUpdateFormSet = modelformset_factory(
        model=Permission,
        form=MultiPermissionForm,
        extra=0)
    if _type is not None and _type == 'update' and request.method == 'POST':
        formset_update = PermissionUpdateFormSet(request.POST)
        if formset_update.is_valid():
            formset_update.save()
            return redirect(customReverse(request, 'rbac:list_menu'))
    else:
        formset_update = PermissionUpdateFormSet(queryset=update_queryset)

    return render(request, 'rbac/operate_multi_permission.html', locals())

class RoleList(ListView):
    model = Role

    def get_context_data(self, **kwargs):
        context = super(RoleList, self).get_context_data(**kwargs)
        context['form'] = RoleForm()
        return context

class RoleCreate(CreateView):
    model = Role
    form_class = RoleForm

class RoleUpdate(UpdateView):
    model = Role
    form_class = RoleForm
    template_name = 'rbac/edit.html'

class RoleDelete(DeleteView):
    model = Role
    success_url = reverse_lazy('rbac:list_role')

def assignPermission(request):
    user_id = request.GET.get('uid')
    user_list = MyUser.objects.all()
    if user_id is not None:
        user_obj = user_list.get(pk=user_id)
    else:
        user_obj = None

    role_id = request.GET.get('rid')
    role_list = Role.objects.all()
    if role_id is not None:
        role_obj = role_list.get(pk=role_id)
    else:
        role_obj = None

    user_roles = user_obj.role.all() if user_id else Role.objects.none()
    user_role_list = [i.id for i in user_roles] if user_roles else []

    # Save roles belong to user_obj
    if request.method == 'POST' and request.POST.get('type') == 'role':
        posted_role_list = request.POST.getlist('role')
        user_obj.role.set(posted_role_list)
        time.sleep(2)
        return redirect(request.get_full_path())

    # Save permissions belong to its role
    if request.method == 'POST' and request.POST.get('type') == 'permission':
        posted_permission_list = request.POST.getlist('permission')
        role_obj.purview.set(posted_permission_list)
        time.sleep(2)
        return redirect(request.get_full_path())

    # When chose a role, show all permissions belong to it,
    # otherwise to a user
    if role_obj:
        user_permission_list = [perm.id for perm in role_obj.purview.all()]
    elif user_obj:
        user_permission_list = [item['purview'] for item in user_obj.role.values('purview')]
    else:
        user_permission_list = list()

    # One grade menu
    all_menu_list = Menu.objects.values('id', 'title')
    all_menu_dict = dict()
    for item in all_menu_list:
        item['children'] = list()
        all_menu_dict[item['id']] = item

    # Second grade menu
    all_second_menu_list = Permission.objects.filter(menu__isnull=False).values('id', 'description', 'menu_id')
    all_second_menu_dict = dict()
    for s_item in all_second_menu_list:
        s_item['children'] = list()
        all_second_menu_dict[s_item['id']] = s_item
        menu_id = s_item['menu_id']
        all_menu_dict[menu_id]['children'].append(s_item)
        # all_menu_dict[menu_id] == all_menu_dict[item['id']]

    # All permissions which can not be menu
    all_permission_list = Permission.objects.filter(menu__isnull=True).values('id', 'description', 'related_id_id')
    for p_item in all_permission_list:
        related_id = p_item['related_id_id']
        if related_id is not None:
            all_second_menu_dict[related_id]['children'].append(p_item)
            # all_second_menu_dict[related_id] == all_second_menu_dict[s_item['id']] == s_item
            # all_menu_dict[menu_id]['children'].append(all_second_menu_dict[related_id])

    '''

templates/asset/asset_edit.html
{% extends "base.html" %}
{% block msg %}{% include "message.html" %}{% endblock %}
{% block content %}
  <form method="post" action="" class="form-horizontal" role="form">
    <div class="form-group">
      <label class="col-sm-2"></label>
      <div class="col-md-6 col-sm-10">
        <h3>修改主机的基本信息</h3>
      </div>
    </div>
    {% csrf_token %}
    {% include "forms.html" %}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">提交</button>
        <a class="btn btn-default" href="{% url 'list' %}">取消</a>
      </div>
    </div>
  </form>
{% endblock %}

templates/asset/asset_list.html
{% extends "base.html" %}
{% load customfilters %}
{% block msg %}{% include "message.html" %}{% endblock %}
{% block head %}
<link rel="stylesheet" href="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css">
<script src="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script>
$(function () {
    $("a.delete").click(function (e) {
        var action = confirm("确认删除？");
        if (action == false) {
            e.preventDefault()
        }
    });
    function findValue(id) {
        var value = $("#" + id).val();
        return value
    }
    function changeValue() {
        var idc_name = findValue("aname");
        var type = findValue("atype");
        var host = findValue("host");
        var env = findValue("env");
        var status = findValue("status");
        var param = $.param({
            aname: idc_name,
            atype: type,
            host: host,
            env: env,
            status: status
        })
        var url = "{% url 'list' %}" + "?" + param;
        window.location.href = url;
    }
    function getURLParam(name) {
        var r = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
        var s = window.location.search.substr(1).match(r);
        if (s !== null) {
            return decodeURI(s[2])
        }
        else {
            return null
        }
    }
    var selectList = ["aname", "atype", "host", "env", "status"];
    function setValue() {
        $.each(selectList, function (index, value) {
            var val = getURLParam(value);
            $.each($("#" + value).children(), function (index, value) {
                if ($(this).val() == val) {
                    $(this).attr("selected", true);
                    return
                }
            })
        })
    }
    $("#aname").change(function () {
        changeValue()
    });
    $("#atype").change(function () {
        changeValue()
    });
    $("#host").change(function () {
        changeValue()
    });
    $("#env").change(function () {
        changeValue()
    });
    $("#status").change(function () {
        changeValue()
    });

    $.ajax({
        type: "GET",
        url: "{% url 'hostname' %}",
        dataType: "json",
        success: function (response) {
            $("input[name=keyword]").autocomplete({
                source: response,
                autoFocus: true
            })
        }
    });

    $(".cancel-select button").click(function () {
        $.each(selectList, function (index, value) {
            $("#" + value + " > option").first().prop("selected", "true");
        });
        window.location.href = "{% url 'list' %}"
    })
})
</script>
<style>
.search {
  float: right;
}

.table-auto {
  width: 100%;
}
</style>
{% endblock %}
{% block content %}
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">
        <a href="#tips" data-toggle="collapse" data-parent="#tip">查看提示</a>
      </h3>
    </div>
    <div id="tips" class="panel-collapse collapse">
      <div class="panel-body">
        <p class="tip"><span>有选择下拉菜单的情况下暂时不提供分页功能</span></p>
        <p class="tip"><span>搜索结果暂时不考虑加入分页功能</span></p>
      </div>
    </div>
  </div>

  <div class="search">
    <form action="" method="post" id="search-form">
      {% csrf_token %}
      <div class="input-group">
        <input type="search" class="form-control" name="keyword" placeholder="主机名">
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="icon icon-search"></i></button>
        </span>
      </div>
    </form>
  </div>

  <div class="select-header">
    <select id="aname">
      <option value="">机房</option>
      {% for idc in idc_list %}
        <option value="{{ idc.id }}">{{ idc.name }}</option>
      {% endfor %}
    </select>
    <select id="atype">
      <option value="">资产类型</option>
      <option value="1">虚拟机</option>
      <option value="2">路由器</option>
      <option value="3">交换机</option>
      <option value="4">其他</option>
    </select>
    <select id="host">
      <option value="">宿主机</option>
      {% for ps in ps_list %}
        <option value="{{ ps.id }}">{{ ps.ip }}</option>
      {% endfor %}
    </select>
    <select id="env">
      <option value="">系统环境</option>
      <option value="1">生产环境</option>
      <option value="2">测试环境</option>
    </select>
    <select id="status">
      <option value="">资产状态</option>
      <option value="1">已使用</option>
      <option value="2">未使用</option>
      <option value="3">待回收</option>
    </select>
    <button class="btn btn-link" type="button">清空选择</button>
  </div>

  <div class="table-responsive">
    <table class="table table-hover table-bordered table-auto">
      <caption>主机详细信息列表</caption>
      <thead>
        <tr>
          <th>ID</th>
          <th>电信IP</th>
          <th>联通IP</th>
          <th>机房</th>
          <th>主机名</th>
          <th>CPU</th>
          <th>内存(GB)</th>
          <th>硬盘(GB)</th>
          <th>操作系统</th>
          <th>机器状态</th>
          <th>主机类型</th>
          <th>运行环境</th>
          <th>宿主机</th>
          <th>备注</th>
          {% if request|has_permission:'修改服务器' or request|has_permission:'删除服务器' %}
            <th>操作</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for asset in asset_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ asset.ip }}</td>
            <td>{{ asset.other_ip }}</td>
            <td>{{ asset.idc }}</td>
            <td>{{ asset.hostname }}</td>
            <td>{{ asset.cpu }}</td>
            <td>{{ asset.memory }}</td>
            <td>{{ asset.disk }}</td>
            <td>{{ asset.system }}</td>
            <td>{{ asset.get_status_display }}</td>
            <td>{{ asset.get_asset_type_display }}</td>
            <td>{{ asset.get_env_display }}</td>
            <td>{{ asset.host }}</td>
            <td>{{ asset.comment }}</td>
            {% with perm_edit=request|has_permission:'修改服务器' perm_delete=request|has_permission:'删除服务器' %}
              {% if perm_edit or perm_delete %}
                <td class="action">
                  {% if perm_edit %}
                    <a href="{% url 'edit' asset.id %}" class="btn btn-info btn-sm">编辑</a>
                  {% endif %}
                  {% if perm_delete %}
                    <a href="{% url 'del' asset.id %}" class="delete btn btn-danger btn-sm">删除</a>
                  {% endif %}
                </td>
              {% endif %}
            {% endwith %}
          </tr>
        {% endfor %}  
      </tbody>  
    </table>
  </div>

  <div class="pull-right">
    {% ifequal flag 1 %}
      <ul class="pager">
        {% if asset_list.has_previous %}
          <li><a href="?page={{ asset_list.previous_page_number }}" class="previous">上一页</a><li>
        {% endif %}
        {% for page in page_list %}
          {% ifequal page asset_list.number %}
            <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li><a href="?page={{ page }}">{{ page }}</a><li>
          {% endifequal %}
        {% endfor %}
        {% if asset_list.has_next %}
          <li><a href="?page={{ asset_list.next_page_number }}" class="next">下一页</a><li>
        {% endif %}
      </ul>
    {% endifequal %}
  </div>

<script>
    setTimeout(function () {
      init()
    }, 200);

    function getUrlParms(name){
        var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
        var r = window.location.search.substr(1).match(reg);
        if(r != null) {
            return decodeURI(r[2])
        }
        else {
            return null
        }
    }  
  
    function init(){
        var s;
        var selectList = ["aname","atype","host","env","status"];
        for(s in selectList){
            var obj = document.getElementById(selectList[s]);
            var val = getUrlParms(selectList[s]);
            for(var i=0; i<obj.options.length; i++){ 
                if(obj.options[i].value == val){ 
            	    obj.options[i].selected = true; 
            	    break; 
            	} 
            }
    }
            }
</script>
{% endblock %}

templates/asset/idc.html
{% extends "base.html" %}
{% load customfilters %}
{% block msg %}{% include "message.html" %}{% endblock %}
{% block head %}
<script>
    $(function () {
        $("a.delete").click(function (e) {
            var action = confirm("确认删除？");
            if (action == false) {
                e.preventDefault()
            }
        })
    })
</script>
{% endblock %}
{% block content %}
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-auto">
      <caption>IDC详细信息</caption>
      <thead>
        <tr>
          <th>ID</th>
          <th>IDC名称</th>
          <th>机房地址</th>
          <th>联系人</th>
          <th>联系方式</th>
          <th>机房带宽</th>
          <th>IP地址段</th>
          <th>备注</th>
          {% if request|has_permission:'修改机房' or request|has_permission:'删除机房' %}
            <th>操作</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for idc in idc_list %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ idc.name }}</td>
            <td>{{ idc.address }}</td>
            <td>{{ idc.linkman }}</td>
            <td>{{ idc.ci }}</td>
            <td>{{ idc.bandwidth }}</td>
            <td>{{ idc.ip_segment }}</td>
            <td>{{ idc.comment }}</td>
            {% with perm_edit=request|has_permission:'修改机房' perm_delete=request|has_permission:'删除机房' %}
              {% if perm_edit or perm_delete %}
                <td class="action">
                  {% if perm_edit %}
                    <a href="{% url 'edit_idc' idc.id %}" class="btn btn-info btn-sm">编辑</a>
                  {% endif %}
                  {% if perm_delete %}
                    <a href="{% url 'del_idc' idc.id %}" class="delete btn btn-danger btn-sm">删除</a>
                  {% endif %}
                </td>
              {% endif %}
            {% endwith %}
          </tr>
        {% endfor %}   
      </tbody> 
    </table>
  </div>
{% endblock %}