cmdb/urls.py
from views import *
from django.conf.urls import url
from django.contrib import admin
from views import CustomLoginView
from django.conf.urls import include
from django.views.static import serve
from django.contrib.auth.views import logout_then_login

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^asset/', include('asset.urls')),
    url(r'^salt/', include('salts.urls')),
    url(r'^zabbix/', include('zabbix.urls')),
    url(r'^permission/', include('rbac.urls', namespace='rbac')),
    url(r'^$', index, name='index'),
    url(r'login/$', CustomLoginView.as_view(), name='loginview'),
    url(r'^logout/$', logout_then_login, name='logoutview'),
    url(r'^image/$', image, name='image'),
    url(r'^verify/$', verify, name='verify'),
    url(r'^password/$', verify_password, name='password'),
    url(r'^tpl/(\w+.(xls|xlsx))$', tpl_download, name='tpl'),
    url(r'^oauth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^(?P<path>favicon.ico)/$', serve, {
        'document_root': 'shared_static'
    }),
]

rbac/urls.py
from django.conf.urls import url, include
from views import *


urlpatterns = [
    url(r'^menu/list/$', listMenu, name='list_menu'),
    url(r'^menu/add/$', addMenu, name='add_menu'),
    url(r'^menu/edit/(?P<pk>\d+)/$', editMenu, name='edit_menu'),
    url(r'^menu/delete/(?P<pk>\d+)/$', deleteMenu, name='delete_menu'),
    url(r'^second/menu/add/(?P<mid>\d+)/$', addSecondGradeMenu, name='add_second_menu'),
    url(r'^second/menu/edit/(?P<pk>\d+)/$', editSecondGradeMenu, name='edit_second_menu'),
    url(r'^second/menu/delete/(?P<pk>\d+)/$', deleteSecondGradeMenu, name='delete_second_menu'),
    url(r'^add/(?P<sid>\d+)/$', addPermission, name='add_permission'),
    url(r'^edit/(?P<pk>\d+)/$', editPermission, name='edit_permission'),
    url(r'^delete/(?P<pk>\d+)/$', deleteSecondGradeMenu, name='delete_permission'),
    url(r'multi/permissions/$', multiPermission, name='multi-permission'),
    url(r'^role/list/$', RoleList.as_view(), name='list_role'),
    url(r'^role/add/$', RoleCreate.as_view(), name='add_role'),
    url(r'^role/edit/(?P<pk>\d+)/$', RoleUpdate.as_view(), name='edit_role'),
    url(r'^role/delete/(?P<pk>\d+)/$', RoleDelete.as_view(), name='delete_role'),
    url(r'^assign/permissions/$', assignPermission, name='assign-permission'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head lang="zh-cn">
    {% load static %}
    <meta charset="utf8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 响应式设计标签 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ZUI 标准版压缩后的 CSS 文件 -->
    <link rel="stylesheet" href="//cdn.bootcss.com/zui/1.8.1/css/zui.min.css">

    <!-- ZUI Javascript 依赖 jQuery -->
    <script src="//cdn.bootcss.com/zui/1.8.1/lib/jquery/jquery.js"></script>
    <!-- ZUI 标准版压缩后的 JavaScript 文件 -->
    <script src="//cdn.bootcss.com/zui/1.8.1/js/zui.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/main.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
{% block msg %}{% endblock %}
{% block header %}
  {% include "header.html" %}
{% endblock %}
  <div class="container">
    <div class="left">
      {% include "sidebar.html" %}
    </div>
  
    <div class="right">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>

templates/forms.html
{% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}" class="col-sm-2">{{ field.label }}</label>
    <div class="col-md-6 col-sm-10">
      {{ field }}
      {% if field.errors %}
        <div class="{% if field.errors %} help-block {% endif %}">
          {% for error in field.errors %}
            <span class="text-danger">{{ error }}</span>
          {% endfor %}
        </div>
      {% endif %}
      {% if field.help_text %}
        <div class="help-block">{{ field.help_text|safe }}</div>
      {% endif %}
    </div>
  </div>
{% endfor %}

templates/header.html
{% load hightlight from customfilters %}
<div class="header">
  <div id="global-nav" class="global_nav">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- 导航头部 -->
        <div class="navbar-header">
          <!-- 移动设备上的导航切换按钮 -->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-example">
            <span class="sr-only">切换导航</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- 品牌名称或logo -->
          <a class="navbar-brand" href="#">ZUI</a>
        </div>
        <!-- 导航项目 -->
        <div class="collapse navbar-collapse navbar-collapse-example">
          <!-- 一般导航项目 -->
          <ul class="nav navbar-nav">
            <li{% if request|hightlight %} class="active"{% endif %}><a href="{% url 'index' %}">项目</a></li>
            <li{% if request|hightlight %} class="active"{% endif %}><a href="{% url 'rbac:list_menu' %}">权限管理</a></li>
          </ul>
          <!-- 右侧的导航项目 -->
          <ul class="nav navbar-nav navbar-right">
            <li><a id="admin" href="javascript:void(0);" onclick="document.getElementById('admin').href = '/admin';"><i class="icon icon-dashboard"></i> 管理后台</a></li>
            <li><a href="{% url 'logoutview' %}"><i class="icon icon-off"></i> 注销</a></li>
          </ul>
        </div>
        <!-- END .navbar-collapse -->
      </div>
    </nav>
  </div>
</div>

templates/index.html
{% extends "base.html" %}
{% load static customfilters %}
{% block head %}
   <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/zui/1.8.1/lib/dashboard/zui.dashboard.min.css"/>
   <script src="https://cdn.bootcss.com/zui/1.8.1/lib/dashboard/zui.dashboard.min.js"></script>
<script>
    $(function () {
        $('#dashboard').dashboard({
            draggable: true,
            height: 100
        })
    })
</script>
{% endblock %}
{% block content %}
  <div id="dashboard" class="dashboard dashboard-draggable">
    <section class="row">
      <div class="col-md-3 col-sm-6">
        <div class="panel" data-id="1">
          <div class="panel-heading">
            <i class="icon icon-server"></i>
            <span class="title">IDC总数</span>
          </div>
          <div class="panel-body">
            <h2><a href="{% url 'idc' %}" style="color: #333;">{{ idc_number }}</a></h2>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="panel" data-id="2">
          <div class="panel-heading">
            <i class="icon icon-server"></i>
            <span class="title">物理服务器数量</span>
          </div>
          <div class="panel-body">
            <h2><a href="{% url 'ps' %}" style="color: #333;">{{ ps_number }}</a></h2>    
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="panel" data-id="3">
          <div class="panel-heading">
            <i class="icon icon-server"></i>
            <span class="title">资产总数</span>
          </div>
          <div class="panel-body">
            <h2><a href="{% url 'list' %}" style="color: #333;">{{ host_number }}</a></h2>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="panel" data-id="4">
          <div class="panel-heading">
            <i class="icon icon-user"></i>
            <span class="title">当前用户</span>
          </div>
          <div class="panel-body">
            <h2>{{ online_user }}</h2>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/message.html
{% if messages %}
  {% for message in messages %}
    {% ifequal message.tags "info" %}
      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message.message }}
      </div>
    {% endifequal %}
    {% ifequal message.tags "success" %}
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message.message }}
      </div>
    {% endifequal %}
    {% ifequal message.tags "warning" %}
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message.message }}
      </div>
    {% endifequal %}
    {% ifequal message.tags "error" %}
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message.message }}
      </div>
    {% endifequal %}
  {% endfor %}
{% endif %}

templates/sidebar.html
<div class="sidebar">
  <nav class="menu" data-ride="menu">
    <ul id="treeMenu" class="tree tree-menu" data-ride="tree">
      <li><a href="{% url 'index' %}"><i class="icon icon-home"></i>仪盘表</a></li>
      <li>
        <a href="javascript:void(0);"><i class="icon icon-play"></i>IDC机房</a>
        <ul>
          <li><a href="{% url 'idc' %}"><i class="icon icon-info-sign"></i>机房信息</a></li>
          <li><a href="{% url 'add_idc' %}"><i class="icon icon-edit-sign"></i>增加机房</a></li>
        </ul>
      </li>
      <li>
        <a href="javascript:void(0);"><i class="icon icon-server"></i>物理服务器</a>
        <ul>
          <li><a href="{% url 'ps' %}"><i class="icon icon-info-sign"></i>服务器列表</a></li>
          <li><a href="{% url 'add_ps' %}"><i class="icon icon-edit-sign"></i>增加服务器</a></li>
        </ul>
      </li>
      <li>
        <a href="javascript:void(0);"><i class="icon icon-server"></i>资产管理</a>
        <ul>
          <li><a href="{% url 'list' %}"><i class="icon icon-info-sign"></i>资产列表</a></li>
          <li><a href="{% url 'add' %}"><i class="icon icon-edit-sign"></i>增加资产</a></li>
        </ul>
      </li>
      <li>
        <a href="javascript:void(0);"><i class="icon icon-play"></i>saltstack</a>
        <ul>
          <li><a href="{% url 'install' %}"><i class="icon icon-cogs"></i>安装客户端</a></li>
          <li><a href="{% url 'collect' %}"><i class="icon icon-info-sign"></i>收集信息</a></li>
          <li><a href="{% url 'command' %}"><i class="icon icon-angle-right"></i>执行命令</a></li>
          <li><a href="{% url 'push' %}"><i class="icon icon-copy"></i>文件推送</a></li>
          <li><a href="{% url 'script' %}"><i class="icon icon-angle-right"></i>执行脚本</a></li>
        </ul>
      </li>
      <li>
        <a href="javascript:void(0);"><i class="icon icon-play"></i>zabbix</a>
        <ul>
          <li><a href="{% url 'ADD' %}"><i class="icon icon-edit-sign"></i>添加主机</a></li>
          <li><a href="{% url 'delete' %}"><i class="icon icon-warning-sign"></i>删除主机</a></li>
        </ul>
      </li>
    </ul>
  </nav>
  <footer>
    <div class="footer">
      <p class="text-muted small">版本 <span class="doc-version">0.1.0</span></p>
    </div>
  </footer>
</div>